<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="13.0.1" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
      <PackageReference Include="Netmentor.ROP" Version="1.4.0" />
      <PackageReference Include="SixLabors.ImageSharp" Version="3.1.6" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TiaSoftBackend.Data\TiaSoftBackend.Data.csproj" />
      <ProjectReference Include="..\TiaSoftBackend.DTOs\TiaSoftBackend.DTOs.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Users\" />
    </ItemGroup>

</Project>
